name: publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup snaps
        run: |
          sudo snap install jq
          sudo snap install yq
      - uses: actions/checkout@master
      - name: Fetch Metanorma container
        uses: docker://metanorma/mn:latest
      - name: Build document in the Metanorma container
        env:
          METANORMA_DOCKER: metanorma/mn:latest
        run: |
          make clean all publish
      - uses: actions/upload-artifact@master
        with:
          name: published
          path: published

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published
    - name: deploy-to-gh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-gh-pages.sh | bash"
